version: '3.5'

services:

  something-clever:
    container_name: notes
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
      # to run: docker-compose up -d --build
